### ISSUE TITLE
Why not use tj/co ?

### ISSUE THREAD

**Issue by egoist** [djyde/node-earthlive#2]
I noticed that you're using Promise a lot, so why not use tj/co to write non-blocking code?

**Comment by egoist** [comment]
If you don't mind I'd like to make a PR :wave: :joy:

**Comment by egoist** [comment]
ok, `co` may not be a must, but I find `downloadPiece().then(()=> generate().then(()=> setWallpaper()))` really hard to read for me..

**Comment by egoist** [comment]
![image](https://cloud.githubusercontent.com/assets/8784712/11843513/f8d38696-a444-11e5-86b6-996334835a5b.png)
:sob:

**Comment by djyde** [comment]
It might be a bug of node-images
